# Generated by Django 5.2 on 2025-04-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
